import Image from 'next/image'
import Link from 'next/link'
import "styles/globals.css"

export const metadata = {
  title: "Eric's, Blog",
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  const header = (
     <header className='text-center font-bold bg-slate-800 p-8 my-6 rounded-md'>
      <div>
        <Image src="/logo.png" alt="Eric's Blog" width={40} height={40} className='mx-auto' />
        <Link href="/">
            <h1 className="text-2xl text-white font-bold mt-4">Eric's Blog</h1>
        </Link> 
        <p className='text-slate-300'>Welcome to my Blog!</p>
      </div>
     </header>
  )

   const footer = (
     <footer>
       <div className='border-t border-slate-400 text-center text-slate-400 mt-12 py-6'>
         <br />
         <p>Made by E. Marshall 2023</p>
      </div>
    </footer>
  )
  
  return (
    <html lang="en"> 
      <body>
        <div className='mx-auto max-w-2xl px-6'>
          {header}
          {children}
          {footer}
        </div>
      </body>   
    </html>
  )
}

